adobe/elixir-styler

README.md
lib/style/simple.ex
test/style/simple_test.exs

implements a rule replacing `Credo.Check.Readability.LargeNumbers`

Add number rewrites in "Simple" style

---

lib/style/simple.ex
lib/zipper.ex
test/zipper_test.exs

Remove nil values for l/r subtrees in zipper metadata
h/t @sega-yarkin for pointing out the issue with the spec

Zipper: remove nil left and right subtree types, optimize up/leftmost/rightmost

---

lib/mix/tasks/style.ex

Adds stdin/stdout interactions to match the formatter
```bash
➜  styler git:(me/stdin) ✗ mix format -
defmodule A do
alias C.{F, E}
alias B
alias A
end
defmodule A do
alias C.{F, E}
alias B
alias A
end
➜  styler git:(me/stdin) ✗ mix style -
defmodule A do
alias C.{F, E}
alias B
alias A
end
defmodule A do
alias B
alias C.E
alias C.F
alias A
end
```

`mix style -`: read/write stdin/stdout like formatter

---

lib/mix/tasks/style.ex
lib/style.ex
lib/style/defs.ex
lib/style/module_directives.ex
lib/style/pipes.ex
lib/style/simple.ex
lib/zipper.ex
test/support/style_case.ex

zipper traversal is now powered by `traverse_while/3`, and all styles are forced to acknowledge the new shape - no more hiding behind `wrap_run`
```elixir
@callback run(Zipper.zipper(), context()) :: {Zipper.command(), Zipper.zipper(), context()}
```
future features are likely to work with `comments`; some may want the filename (module directives, for example) and who knows what else we'll add in. passing a map accumulator of context or state gives us a decently future-proof api

Change `Style.run` type spec to explicitly rely on `Zipper.traverse_while/3`

---

lib/style/pipes.ex
test/style/pipes_test.exs

Keep single-pipe function call rewrites on one line

---

lib/style/module_directives.ex
lib/zipper.ex
test/style/module_directives_test.exs
test/support/style_case.ex
test/zipper_test.exs

Changes:
- directives: will remove newlines between groups: no more empty space between your aliases etc
- directives: orders different directives in all contexts, not just module bodies (functions, quote do, etc, will now be organized)
- rename `Zipper.make_node/2` -> `Zipper.replace_children/2`, which made it a little clearer to me what problems it can solve! 
- `@moduledoc` `@behaviour` and `@shortdoc` will not be noticed outside of a defmodule if they are alone in the context with no `use/alias/import/require`. you can see this in the implementation of run: it only catches `defmodule, use, alias, import, require`. i feel like this is.. too much of an edgecase to deal with for the moment, as it'll only occur in super weird macro situations? ala `quote do @moduledoc ...; @behaviour ...; …

Optimize module directives, remove concept of directive groups

---

lib/style/pipes.ex
test/style/pipes_test.exs
test/support/style_case.ex

Closes #15 
- `a |> b` created invalid ast due to `b` having ast `{:b, _meta, nil = _args}`, causing us to create the improper list `[a | nil]`
- `==` was mistakenly not included in the list of math/comparison operators that are valid starts to a pipe
also snuck in another QOL improvement for helping show invalid AST when running tests

Fix Pipes Bugs

---

CHANGELOG.md
lib/style.ex
lib/style/module_directives.ex
lib/style/pipes.ex
test/style/module_directives_test.exs

Found this while looking into unifying "wrap this node in a `:__block__` parent" code. Extracting that from the Pipes rule and using it universally will fix this bug in module directives

bugfix: moduledirectives weird parents

---

CHANGELOG.md
README.md
lib/style.ex
lib/style/pipes.ex
test/style/pipes_test.exs

See changelog! =)
Like with moduledirectives, as every pipe now had to have the same code run on it, it made sense to rewrite pipes to have a single entry point that step-by-step handled all the cases. I hope that the result is a more immediately-followable algorithm with less fanciness happening than before
Please lemme know where we need comments! It's all so fresh in my head right now that it seems fine as-is ;)
As I was doing these rewrites, I imagined places that our pipes rule was already failing + added tests for those as well. So this probably fixed bugs we didn't know we had along the way ^.^

`Pipes`: `Enum`-optimizing rewrites

---

CHANGELOG.md
lib/style/pipes.ex
test/style/pipes_test.exs

Realized we might as well ship it for all cases, not just when `Enum.map` comes ahead of it!

Pipes: rewrite Enum.into oneliners to use Map.new instead

---

lib/style/pipes.ex
test/style/pipes_test.exs

Closes #24
This error makes me think that it's likely that other macro DSLs will work poorly with the pipes op, but we'll see what crops up

Bug: include Ecto.Query.from as a valid pipe start

---

lib/style/module_directives.ex
test/style/module_directives_test.exs

This fixes an error that occurs when formatting a module with an alias on its submodules:
```elixir
defmodule Test do
alias __MODULE_.{A, B}
end
```

Fix aliases using __MODULE__

---

lib/mix/tasks/style.ex
lib/style_error.ex
lib/styler.ex

The idea is, bugs in Styler shouldn't cause folks' CI to fail.
- styles which raise during `mix format` will now just be skipped, instead of halting all other styles + formatting on that file
- `mix style` still fails as before
- asks folks to raise an issue when they encounter an error
**`mix format` example**
**`mix style` example**

Better error handling: Skip failed styles but still format files

---

lib/style/single_node.ex
test/style/single_node_test.exs

The real fix here is to not write code that way, but at least people won't get an endlessly changing line

Fix toggle state from RHS match when `var = _ ->`

---

CHANGELOG.md
lib/style/single_node.ex
test/style/single_node_test.exs

Ref #45 
I think I might need `if meta[:delimiter] and Enum.all?(chars, &is_integer/1) do` for this to not rewrite things we don't want to, but need more testing and thinking time

rewrite charlists to use ~c sigil

---

lib/style/single_node.ex
test/style/single_node_test.exs

Double quotes are more commonly used. This adds a test for embedded double quotes in the original string, but Elixir handles this case already.

Use double quotes for ~c sigil

---

lib/style/module_directives.ex
test/style/module_directives_test.exs

Closes #29
See expansive comment in code for reasoning + algorithm

Fix ModuleDirectives comments 

---

lib/style/module_directives.ex
test/style/module_directives_test.exs

problem still happens when the last directive was moved from below, as it isn't paired with a subsequent ast node

fix module directives comment edge case

---

.github/workflows/ci.yml
lib/style/single_node.ex
test/style/single_node_test.exs

This PR includes some improvements when interacting with `Date` or `DateTime`.
* Elixir v1.15 introduced `{Date,DateTime,NaiveDateTime,Time}.{after?/2,before?/2}`. This means that we could improve the readability of some Date/Time comparisons.
* I also took the chance to transform some `Timex` `defdelegate` to their native equivalent.
Finally, most of these additions only apply if we're running on Elixir v1.15, so I added new entries for Elixir and OTP matrix for CI purposes.

Improve Date/DateTime interactions

---

lib/style/pipes.ex

- Added missing infix operators.
I am uncertain if this is the correct solution, but when I ran `mix format`, I encountered errors related to the usage of `and`, `or`, `!=`, `!==`, `===` operators.
Sample Code Snippet: 
```
((id == "" or id == requested_id) and (type == "" or type == requested_type))
|> foo()
```
After `mix format`:
```
(id == "" or id == requested_id)
|> and(type == "" or type == requested_type)
|> foo()
```
As you can observe, this syntax is not valid. Therefore, I added these operators in `infix_ops` list.

fix: add missing infix operators

---

CHANGELOG.md
README.md
lib/style/single_node.ex
lib/styler.ex
test/style/single_node_test.exs

rewrite two credo rules:
- Credo.Check.Readability.WithSingleClause
- Credo.Check.Refactor.WithClauses
There's a lot of weird ways `with` statements can be written.
Need to run this on a big codebase and see what goes kaboom... (I don't have any `with ..., do:` tests, for one)
**update**: Ran against a large codebase without errors: :shipit:

with statement rewrites

---

lib/style/pipes.ex
test/style/pipes_test.exs

This patch fixes a crash where macros with a single do block argument
that were being piped into a function.
Now, the following code transformation will occur instead of a crash:
```elixir
foo do
"hi"
end
|> IO.puts()
IO.puts(
foo do
"hi"
end
)
```

fix: macros with only 1 block argument

---

CHANGELOG.md
lib/style/blocks.ex
test/style/blocks_test.exs

closes #84
leaving this as a PR for a bit while I stew

with statement: drop singleton identity else. closes #84

---

.github/workflows/ci.yml
CHANGELOG.md
lib/style/single_node.ex
test/style/single_node_test.exs

noticed `''` being rewritten to `~c""` after updating elixir to 1.15. wondered what bug existed in styler that it required being on 1.15 to make that rewrite... and then realized elixir itself is now doing this!

empty charlists

---

CHANGELOG.md
lib/style/blocks.ex
test/style/blocks_test.exs

- happier comments with `with` statement when head clauses get moved into the body of the with statement
- handle edge cases where the `with` statement should just be deleted entirely, and its clauses written as normal code

with statements: happier comments and sad edge cases

---

lib/style/module_directives.ex
test/style/module_directives_test.exs

keep module callback ordering relative to `use` directives.

---

lib/style/pipes.ex
test/style/pipes_test.exs

:wave: first and foremost, thanks for creating and maintaining styler! We use it in a large codebase where i stumbled over some occurrences of named function references passed into `Kernel.then/2`. I couldn't figure when that would be useful so I am opening this PR proposing to have it handled by styler. I've tested this change in our codebase but am happy to get any pointers on what i could've missed!
Let me know if you'd consider adding this to styler (or not! :)

Rewrite then/2 when function is a named function reference

---

lib/style/pipes.ex
test/style/pipes_test.exs

I _guess_ that's the only operators that need tweaking? feel free to take over the PR :)

fix: fix unary operators in pipes (fixes adobe#128)

---

CHANGELOG.md
README.md
lib/style/module_directives.ex
lib/zipper.ex
test/style/module_directives/alias_lifting_test.exs

Write a Styler style that does the work of `Credo.Check.Design.AliasUsage`, lifting deeply nested aliases by `alias`ing them.
Notably, even if you're running credo's AliasUsage, styler will fix a _lot_ more things. 
This is because styler is fixing things that credo ignores:
1. credo ignores `@module_attribute A.B.C.f()` due to a mistaken report that dialyzer can't understand aliases
2. credo _only_ looks for deep modules being _invoked_. `apply(A.B.C, :f, [])` doesn't set credo off. (credo does complain if the module is the _only_ argument to a function call)
Yes, I thought of at least [_some_](https://github.com/adobe/elixir-styler/pull/135/files#diff-4b219d591161863697d29f166f2980252d9b96b7f8fb045c61af1ef3e9c9e9deR181) of the cases where it _shouldn't_ do that and implemented …

extract alias usage

---

lib/style.ex
lib/style/blocks.ex
lib/style/defs.ex
lib/style/module_directives.ex
lib/style/pipes.ex
lib/style/single_node.ex
lib/style_error.ex
lib/styler.ex
lib/zipper.ex
mix.exs
test/style/blocks_test.exs
test/style/defs_test.exs
test/style/module_directives_test.exs
test/style/pipes_test.exs
test/style/single_node_test.exs
test/style/styles_test.exs
test/support/style_case.ex
test/test_helper.exs
test/zipper_test.exs

```shell
git grep -P '\d{4}\sAdobe' | \
awk -F: '{print $1}' | \
xargs -I {} sh -c 'year=`date +"%Y"`; sed -i -ne "s/[[:digit:]]\{4\}\( Adobe\)/${year}\1/;p" {}'
```

Year bump in copyright declaration

---

CHANGELOG.md
README.md
lib/style/single_node.ex
test/style/single_node_test.exs

styler rewriting strings with many escapes involves running regexes against all string literals to detect too many escapes. was worried regexing like that would be too costly but… i think 3/100ths of a second in a repo as large as we have at frame is acceptable?
```sh
➜  frameio git:(me/styler-test) hyperfine 'mix format' -i --warmup 1 # with string sigils
Benchmark 1: mix format
Time (mean ± σ):      3.589 s ±  0.024 s    [User: 16.577 s, System: 1.975 s]
Range (min … max):    3.556 s …  3.638 s    10 runs
➜  frameio git:(me/styler-test) hyperfine 'mix format' -i --warmup 1 # without string sigils
Benchmark 1: mix format
Time (mean ± σ):      3.553 s ±  0.027 s    [User: 16.527 s, System: 1.977 s]
Range (min … max):    3.516 s …  3.602 s    10 runs
```

rewrite double quote strings with many escapes to use `~s`

---

CHANGELOG.md
lib/style.ex
lib/style/blocks.ex
lib/style/configs.ex
lib/style/module_directives.ex
lib/style/single_node.ex
lib/styler.ex
test/style/configs_test.exs
test/support/style_case.ex

It would be possible to ship this rule as a lint-only, which would assert that when sorted the config file doesn't change. That would unblock it from the following todos:
TODOs

organize config files

---

lib/style/module_directives.ex
lib/styler.ex
lib/styler/config.ex
test/style/module_directives/alias_lifting_test.exs
test/support/style_case.ex

Closes #139
works like
```ex
[
plugins: [Styler],
styler: [alias_lifting_exclude: ~w(Plug Oban Phoenix Ecto GetText)a],
line_length: 1_000_000,
]
```
todos

Add configuration for modules to exclude for alias lifting

---

.formatter.exs
lib/style/module_directives.ex
test/style/module_directives/alias_lifting_test.exs

Closes #151 
two possible fixes:
either don't lift (simple: `if List.first(aliases) in excluded ...`)
or lift but with the combined name. would have to keep track of `aliased` separate form `excluded` so that the name can be combined, and then do a heavier lift on line 241 `new_aliases = ...`

fix: lifting deeply nested aliases of aliases

---

lib/style/pipes.ex
test/style/pipes_test.exs

An expression along the lines of `|> then(&(&1 * 2 / 1))` is currently being formatted as `|> (&1 * 2)` because the pattern match for single-arity functions is a bit too lax.

Fix piped `then` for complex expressions with division by one

---

CHANGELOG.md
lib/style/module_directives.ex
test/style/module_directives_test.exs

Lift attributes to variables

---

CHANGELOG.md
docs/control_flow_macros.md
lib/style/blocks.ex
lib/style/module_directives.ex
lib/style/pipes.ex
test/style/blocks_test.exs
test/style/pipes_test.exs
test/support/style_case.ex

[unless is being deprecated](https://github.com/elixir-lang/elixir/pull/13769#issuecomment-2334878315)
[unless is complex to read](https://github.com/adobe/elixir-styler/issues/190)

Remove unless from codebases

---

CHANGELOG.md
lib/style.ex
lib/style/pipes.ex
test/style/pipes_test.exs

One-line unpiped assignments

---

lib/style/deprecations.ex
test/style/deprecations_test.exs

1.18 hard deprecations

---

CHANGELOG.md
lib/style/comment_directives.ex
lib/styler.ex
test/style/comment_directives_test.exs

introduce `# styler:sort` comment directive

---

lib/style.ex
lib/style/comment_directives.ex
lib/style/configs.ex
lib/style/module_directives.ex
test/style/comment_directives_test.exs
test/style_test.exs

Maintain comment-node relations when applying `#styler:sort` directive

---

.github/workflows/ci.yml

@novaugust how about updating the matrix, dropping Elixir 1.15 in favour of Erlang 26?

ci: update elixir and erlang versions

---

CHANGELOG.md
lib/style/blocks.ex
test/style/blocks_test.exs

fix with to case rewrites when with is keyword with an else stab

---

.github/workflows/ci.yml

Add OTP26/27 to the matrix as 1.17/1.18 support them by default.
Exclude OTP27 for 1.15/1.16

Add OTP26/27 but only run for 1.17/1.18

---

CHANGELOG.md
lib/style.ex
lib/style/configs.ex
test/style/configs_test.exs

Fix long comment mangling bug when ordering sibling AST

---

lib/style/configs.ex
lib/style/module_directives.ex
lib/zipper.ex
test/zipper_test.exs

Running against a large elixir umbrella app, the optimization showed a 50% slow down :O
```
➜ # v1.4.2
➜ hyperfine 'mix format' -i --warmup 1 --runs 32 # v1.4.2
Benchmark 1: mix format
Time (mean ± σ):      1.094 s ±  0.027 s    [User: 0.781 s, System: 0.818 s]
Range (min … max):    1.048 s …  1.155 s    32 runs
➜ # styler main
➜ hyperfine 'mix format' -i --warmup 1 --runs 32 
Benchmark 1: mix format
Time (mean ± σ):      1.534 s ±  0.037 s    [User: 1.009 s, System: 0.979 s]
Range (min … max):    1.475 s …  1.655 s    32 runs
```

Revert "optimize zipper performance"
